compressionLevel: mixed
defaultSemverRangePrefix: ''
enableGlobalCache: false
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.0.2.cjs
packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: '*'
      react: '*'
      react-dom: '*'
