name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Turbo Lint Prettier
        run: yarn turbo:format:prettier
      - name: Turbo Lint ESLint
        run: yarn turbo:lint:eslint
#      - name: Smoke & Acceptance tests
#        run: |
#          yarn build-storybook --quiet
#          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
#            "npx http-server storybook-static --port 6006 --silent" \
#            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
