name: Playwright

on:
  push:
    branches:
      - master
  pull_request: null
  workflow_dispatch: null

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/playwright-bin
  # /ms-playwright/chromium-1084/chrome-linux/chrome
#  PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
#  PLAYWRIGHT_BROWSERS_PATH: "0"

jobs:
  tests:
    name: Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Install Playwright Browsers
        run: yarn dlx playwright install --with-deps
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn turbo:test:playwright:headless
        env:
          SKIP_ENV_VALIDATION: true
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          retention-days: 30
          path: |
            webapps/web1/playwright-report
            webapps/web1/test-results
