name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request: null
  workflow_dispatch: null

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn turbo:test:playwright:headless
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          retention-days: 30
          path: |
            webapps/web1/playwright-report
