name: Playwright

on:
  push:
    branches:
      - master
  pull_request: null
  workflow_dispatch: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(grep "@playwright/test@" yarn.lock | sha256sum)" >> $GITHUB_ENV
      - name: Restore Playwright Browsers cache
        id: cache-playwright-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.cache-playwright-restore.outputs.cache-hit != 'true'
        run: yarn dlx playwright install --with-deps
      - name: Save Playwright Browsers cache
        if: steps.cache-playwright-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ steps.cache-playwright-restore.outputs.cache-primary-key }}
      - name: Run Playwright tests
        run: yarn turbo:test:playwright:headless
        env:
          SKIP_ENV_VALIDATION: true
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          retention-days: 30
          path: |
            webapps/web1/playwright-report
            webapps/web1/test-results
